[package]
name = "minitrace-fbs"
version = "0.1.0"
authors = ["zhongzc <zhongzc_arch@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
